#!/home/pi/.rvm/rubies/ruby-2.0.0-p195/bin/ruby

$:.unshift File.dirname(__FILE__) + "/lib"
require 'app_conf'

Dante.run("alert") do |opts|
  AppConf.setup if ARGV[1] == "setup"
  alert = Alert.new
  alert.start
end

# sudo /home/pi/alert/ruby/alert -d -P /home/pi/alert/ruby/alert.pid -l /home/pi/alert/ruby/logs/output.log 
# sudo /home/pi/alert/ruby/alert -k -P /home/pi/alert/ruby/alert.pid
